language: python

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox

script:
  - tox

after_success:
  - pip install codecov
  - codecov

env:
  global:
    #- TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/
    - TWINE_USERNAME=marcelm
    # TWINE_PASSWORD is set in Travis settings

jobs:
  include:
    - python: "3.5"
      env: TOXENV=py35

    - python: "3.6"
      env: TOXENV=py36

    - python: "3.7"
      env: TOXENV=py37

    - python: "3.8"
      env: TOXENV=py38

    - name: flake8
      python: "3.6"
      env: TOXENV=flake8

    - name: mypy
      python: "3.6"
      env: TOXENV=mypy

    - name: docs
      python: "3.6"
      env: TOXENV=docs

    - stage: deploy
      services:
        - docker
      python: "3.6"
      install: python3 -m pip install Cython twine
      if: tag IS present
      script:
        - |
          python3 setup.py sdist
          ./buildwheels.sh
          ls -l dist/
          python3 -m twine upload dist/*

  allow_failures:
    - python: "nightly"
